export const SITE = {
  name: "Livery",
  domain: "livery.site",
  /** The canonical origin: livery.site redirects here (308), so every canonical, sitemap and share link uses it. */
  url: "https://www.livery.site",
  tagline: "Any website's design, as a skill for your coding agent.",
  description:
    "Turn any website into a design system your AI coding agent can follow. Paste a link and Livery measures its colours, type, spacing, components and motion into an installable kit for Claude Code, Cursor, Codex and Windsurf.",
  /** One quotable sentence: what Livery is (search snippets, AI answers, structured data). */
  definition:
    "Livery is a free tool that turns any public website's design into an installable design kit (a skill) for AI coding agents such as Claude Code, Cursor, Codex and Windsurf, measured from the live site rather than generated by a model.",
  keywords: [
    "design system for AI coding agents",
    "Claude Code skill",
    "Claude Code design",
    "Cursor rules design system",
    "design tokens",
    "website to design system",
    "copy website design",
    "vibe coding design",
    "AI coding agent UI",
    "Codex design kit",
  ],
} as const;

export const BOT = {
  userAgent: "LiveryBot/1.0 (+https://livery.site/bot)",
} as const;

export const THEME_STORAGE_KEY = "livery-theme";

// Builds are expensive (a browser session and a model call); cached kits are free.
export const RATE_LIMITS = {
  build: { windowSeconds: 3600, max: 10 },
} as const;

// Bump when extraction changes; part of the kit cache key, so old kits rebuild on next request.
export const EXTRACTOR_VERSION = Number(process.env.EXTRACTOR_VERSION ?? 1);
export const FLOW_VERSION = 1;

/** The extension's Chrome Web Store page, once it's published (NEXT_PUBLIC_CHROME_EXTENSION_URL). */
export const EXTENSION_STORE_URL = process.env.NEXT_PUBLIC_CHROME_EXTENSION_URL || null;

/** What someone types on /me to confirm deleting their account. */
export const DELETE_ACCOUNT_PHRASE = "delete my account";

/** The person behind Livery: where to say hello and how to support the work. */
export const CREATOR = {
  handle: "@andymarrows",
  x: "https://x.com/andymarrows",
  support: "https://buymeacoffee.com/andymarrow",
} as const;
